# Generated by Django 4.2.7 on 2023-11-14 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaTarjetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'marca_tarjetas',
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=250)),
                ('cvv', models.CharField(max_length=4)),
                ('fecha_otorgamiento', models.DateField()),
                ('fecha_expiracion', models.DateField()),
                ('tipo', models.CharField(max_length=100)),
                ('customer_id', models.ForeignKey(db_column='customerId', on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente')),
                ('marca_tarjeta_id', models.ForeignKey(db_column='marcaTarjetaId', on_delete=django.db.models.deletion.DO_NOTHING, to='tarjetas.marcatarjetas')),
            ],
            options={
                'db_table': 'tarjeta',
            },
        ),
    ]
