# Generated by Django 4.2.7 on 2023-11-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='employee_hire_date',
            field=models.DateField(),
        ),
    ]
